metadata.format.version = "1.1"

[versions]

minestom = "1554487748"
minestomext = "1.2.0"
slf4j = "2.0.11"

# Gradle plugins
blossom = "1.3.0"
shadowJar = "7.0.0"

[libraries]

minestom = { group = "dev.hollowcube", name = "minestom-ce", version.ref = "minestom" }
minestomext = { group = "dev.hollowcube", name = "minestom-ce-extensions", version.ref = "minestomext" }
slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

[bundles]

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
